### PR TITLE
Add clippy and nightly for travis.

### PR DESCRIPTION
**Pull request by ghost**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/service_discovery/16)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @vinipsmaker

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/lib.rs, line 25 [r2]](https://reviewable.io:443/reviews/maidsafe/service_discovery/16#-KAAboP61lIE-EhsaAGM:-KAAboP61lIE-EhsaAGN:-1560954586) ([raw file](https://github.com/maidsafe/service_discovery/blob/f6470c0e5d92ab60ecdee1e204881cd9afdf8f8f/src/lib.rs#L25)):_
;-) nice catch

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/service_discovery/16)_

**Pull request merged**
